version:  '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/user/app
      - /usr/app/node_modules
    ports:
      - 9229:3000
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
networks:
  webnet: