version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/home/app
      - /home/app/node_modules
    ports:
      - 3000:3000
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - db
  db:
    container_name: mongodb
    image: mongo
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=nestapi
    networks:
      - webnet
    ports:
      - 27071:27071
    volumes:
      - data:/home/app/db
networks:
  webnet:
volumes:
  data:
